apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: doro-alpha
resources:
  - namespace.yaml
  - service-accounts.yaml
  - secret-provider-classes.yaml
  - jobs.yaml
images:
  - name: doro-erp-store-access-migration
    newName: 727646470302.dkr.ecr.ap-northeast-2.amazonaws.com/doro-erp-store-access
    newTag: 05418429a849-migration # source-revision: 05418429a84933e4cde415d3232b0ff6184c749c
  - name: doro-erp-commerce-migration
    newName: 727646470302.dkr.ecr.ap-northeast-2.amazonaws.com/doro-erp-commerce
    newTag: 05418429a849-migration # source-revision: 05418429a84933e4cde415d3232b0ff6184c749c
  - name: doro-erp-payment-migration
    newName: 727646470302.dkr.ecr.ap-northeast-2.amazonaws.com/doro-erp-payment
    newTag: 05418429a849-migration # source-revision: 05418429a84933e4cde415d3232b0ff6184c749c
  - name: doro-erp-queue-migration
    newName: 727646470302.dkr.ecr.ap-northeast-2.amazonaws.com/doro-erp-queue
    newTag: 05418429a849-migration # source-revision: 05418429a84933e4cde415d3232b0ff6184c749c
