apiVersion: v1
kind: Service
metadata:
  name: provider-admin
  labels:
    app.kubernetes.io/name: provider-admin
    app.kubernetes.io/part-of: doro-erp-admin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: provider-admin
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
      appProtocol: http
